### ISSUE TITLE
[Korekto][Unit Tests] Validation de la logique du rover

### ISSUE THREAD

**Issue by ledoyen** [AntoineAntix/LeZen#13]
# Liste des vérifications

* :ok: compilation du projet
* :negative_squared_cross_mark: style :
  * `com.esiea.tp4A.CondMvt`
    * **FieldMandatoryModifiersRule**: The field `x` must have modifiers `private`, `final` (line 5)
    * **FieldMandatoryModifiersRule**: The field `y` must have modifiers `private`, `final` (line 6)
    * **FieldMandatoryModifiersRule**: The field `mars` must have modifier `private` (line 7)
  * `com.esiea.tp4A.Jeu`
    * **FieldMandatoryModifiersRule**: The field `positionJoueurs` must have modifiers `private`, `final` (line 13)
    * **FieldMandatoryModifiersRule**: The field `liste` must have modifiers `private`, `final` (line 14)
    * **ExcessiveMethodLengthRule**: Method `genererJoueurs` has **24** lines, exceeding the maximum of 10 (lines 28 to 52)
  * `com.esiea.tp4A.Joueur`
    * **FieldMandatoryModifiersRule**: The field `rover` must have modifier `final` (line 4)
    * **FieldMandatoryModifiersRule**: The field `numJ` must have modifier `final` (line 5)
  * `com.esiea.tp4A.Laser`
    * **FieldMandatoryModifiersRule**: The field `x` must have modifiers `private`, `final` (line 6)
    * **FieldMandatoryModifiersRule**: The field `y` must have modifiers `private`, `final` (line 7)
    * **FieldMandatoryModifiersRule**: The field `mars` must have modifier `private` (line 8)
    * **FieldMandatoryModifiersRule**: The field `range` must have modifier `private` (line 9)
  * `com.esiea.tp4A.Mars`
    * **FieldMandatoryModifiersRule**: The field `maxX` must have modifier `private` (line 12)
    * **FieldMandatoryModifiersRule**: The field `minX` must have modifier `private` (line 13)
    * **FieldMandatoryModifiersRule**: The field `maxY` must have modifier `private` (line 14)
    * **FieldMandatoryModifiersRule**: The field `minY` must have modifier `private` (line 15)
    * **FieldMandatoryModifiersRule**: The field `positionObstacles` must have modifiers `private`, `final` (line 16)
    * **ExcessiveMethodLengthRule**: Method `genererObstacles` has **19** lines, exceeding the maximum of 10 (lines 22 to 41)
  * `com.esiea.tp4A.Rover`
    * **FieldMandatoryModifiersRule**: The field `rMvt` must have modifier `private` (line 8)
    * **FieldMandatoryModifiersRule**: The field `laser` must have modifier `private` (line 9)
  * `com.esiea.tp4A.RoverMovment`
    * **FieldMandatoryModifiersRule**: The field `mvt` must have modifier `private` (line 8)
    * **FieldMandatoryModifiersRule**: The field `direction` must have modifiers `private`, `final` (line 9)

* :negative_squared_cross_mark: couverture par les tests : 81.67 %
* :negative_squared_cross_mark: tests de déplacement basiques
  * **basic_moves_from_center**: [new position after receiving command 'b']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=0, y=-1, direction=NORTH}> but was not.
  * **basic_moves_from_center**: [new position after receiving command 'f']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=0, y=1, direction=NORTH}> but was not.
  * **basic_moves_from_center**: [new position after receiving command 'l']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=0, y=0, direction=WEST}> but was not.
  * **basic_moves_from_center**: [new position after receiving command 'r']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=0, y=0, direction=EAST}> but was not.
  * **complex_moves_from_center**: [new position after receiving command 'fflb']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=1, y=2, direction=WEST}> but was not.
  * **complex_moves_from_center**: [new position after receiving command 'lbblffr']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=2, y=-2, direction=WEST}> but was not.
  * **complex_moves_from_different_origin**: [new position after receiving command 'ff']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=3, y=-3, direction=WEST}> but was not.
  * **complex_moves_from_different_origin**: [new position after receiving command 'lbblffr']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=7, y=-1, direction=SOUTH}> but was not.
  * **unknown_command_should_be_ignored**: [new position after receiving command 'aff']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=-2, y=-1, direction=SOUTH}> but was not.
  * **unknown_command_should_be_ignored**: [new position after receiving command 'f f']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=-2, y=-1, direction=SOUTH}> but was not.
  * **unknown_command_should_be_ignored**: [new position after receiving command 'f,f']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=-2, y=-1, direction=SOUTH}> but was not.
  * **unknown_command_should_be_ignored**: [new position after receiving command 'ff;']  Expecting:  <Position{x=0, y=0, direction=NORTH}> to be equal to:  <Position{x=-2, y=-1, direction=SOUTH}> but was not.

* :black_square_button: tests de la carte sphérique (50x50)
* :black_square_button: tests de la détection d'obstacle
* :black_square_button: tests du laser

_Updated on 2020-04-13T14:41._

**Comment by AntoineAntix** [comment]
Tests effectués

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time

**Comment by ledoyen** [comment]
There is still time
